name: sustain-lc

channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults

dependencies:
  - python=3.11      # or 3.10
  - pytorch
  - pytorch-cuda=12.4
  - libblas=*=*mkl
  - liblapack=*=*mkl
  - matplotlib
  - tensorboard
  - gymnasium
  - pyfmi
  - tqdm
  - casadi
  - scikit-learn
  # - torchviz